# Generated by Django 4.2 on 2024-01-28 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["reservation", "show_session", "row", "seat"]
            },
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
