# Generated by Django 4.2 on 2024-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planetarium",
            "0002_alter_ticket_options_alter_ticket_unique_together",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seatrow",
            constraint=models.UniqueConstraint(
                fields=("planetarium_dome_id", "row_number"),
                name="planetarium_dome_seat_row_number_unique_together",
            ),
        ),
    ]
