# Generated by Django 4.2 on 2024-01-29 20:33

from django.db import migrations, models
import planetarium.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planetarium",
            "0003_seatrow_planetarium_dome_seat_row_number_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=planetarium.models.astronomy_show_image_file_path,
            ),
        ),
    ]
