# Generated by Django 4.2 on 2024-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                blank=True,
                related_name="astronomy_shows",
                to="planetarium.showtheme",
            ),
        ),
    ]
